Repository AdoongE/BE, pull requests merged in 2024-12, with the labels that each got.

#66 Refact : 카테고리, 북마크 부분 리팩토링 #5
  src/main/java/com/adoonge/seedzip/SeedzipApplication.java
  src/main/java/com/adoonge/seedzip/auth/service/AuthService.java
  src/main/java/com/adoonge/seedzip/bookmark/controller/BookmarkController.java
  src/main/java/com/adoonge/seedzip/bookmark/domain/Bookmark.java
  src/main/java/com/adoonge/seedzip/bookmark/dto/response/BookmarkResponse.java
  src/main/java/com/adoonge/seedzip/bookmark/repository/BookmarkRepository.java
  src/main/java/com/adoonge/seedzip/bookmark/service/BookmarkService.java
  src/main/java/com/adoonge/seedzip/category/controller/CategoryController.java
  src/main/java/com/adoonge/seedzip/category/domain/Category.java
  src/main/java/com/adoonge/seedzip/category/domain/Visibility.java
  src/main/java/com/adoonge/seedzip/category/dto/request/AddCategoryRequest.java
  src/main/java/com/adoonge/seedzip/category/dto/request/UpdateCategoryRequest.java
  src/main/java/com/adoonge/seedzip/category/dto/response/CategoryResponse.java
  src/main/java/com/adoonge/seedzip/category/repository/CategoryRepository.java
  src/main/java/com/adoonge/seedzip/category/service/CategoryService.java
  src/main/java/com/adoonge/seedzip/global/config/JpaConfig.java
Labels: Bug 🐞, Refactor ♻️

#67 Refact : 유튜브 추천 로직 정리 (#56)
  src/main/java/com/adoonge/seedzip/summary/controller/SummaryController.java
  src/main/java/com/adoonge/seedzip/summary/dto/request/ChatGPTRequest.java
  src/main/java/com/adoonge/seedzip/summary/dto/response/SummaryResponse.java
  src/main/java/com/adoonge/seedzip/summary/service/SummaryService.java
Labels: Refactor ♻️

#68 Refactor: 이미지 링크 기반 추천 리팩토링
  src/main/java/com/adoonge/seedzip/global/config/SecurityConfig.java
  src/main/java/com/adoonge/seedzip/recommendation/config/OpenAiConfig.java
  src/main/java/com/adoonge/seedzip/recommendation/controller/RecommendationController.java
  src/main/java/com/adoonge/seedzip/recommendation/dto/Message.java
  src/main/java/com/adoonge/seedzip/recommendation/dto/TextMessage.java
  src/main/java/com/adoonge/seedzip/recommendation/dto/request/ChatGPTRequest.java
  src/main/java/com/adoonge/seedzip/recommendation/dto/request/Content.java
  src/main/java/com/adoonge/seedzip/recommendation/dto/request/ImageContent.java
  src/main/java/com/adoonge/seedzip/recommendation/dto/request/ImageMessage.java
  src/main/java/com/adoonge/seedzip/recommendation/dto/request/ImageUrl.java
  src/main/java/com/adoonge/seedzip/recommendation/dto/request/TextContent.java
  src/main/java/com/adoonge/seedzip/recommendation/dto/response/ChatGPTResponse.java
  src/main/java/com/adoonge/seedzip/recommendation/dto/response/Choice.java
  src/main/java/com/adoonge/seedzip/recommendation/dto/response/RecommendationResponse.java
  src/main/java/com/adoonge/seedzip/recommendation/service/RecommendationService.java
  src/main/java/com/adoonge/seedzip/recommendation/service/YouTubeService.java
  src/main/java/com/adoonge/seedzip/summary/controller/SummaryController.java
Labels: Refactor ♻️

#69 Refact : 태그 리팩토링 (#50)
  src/main/java/com/adoonge/seedzip/content/service/ContentsService.java
  src/main/java/com/adoonge/seedzip/tag/controller/TagController.java
  src/main/java/com/adoonge/seedzip/tag/domain/CustomTag.java
  src/main/java/com/adoonge/seedzip/tag/domain/DefaultTag.java
  src/main/java/com/adoonge/seedzip/tag/domain/Tag.java
  src/main/java/com/adoonge/seedzip/tag/domain/UsedDefaultTag.java
  src/main/java/com/adoonge/seedzip/tag/dto/TagResponse.java
  src/main/java/com/adoonge/seedzip/tag/repository/CustomTagRepository.java
  src/main/java/com/adoonge/seedzip/tag/repository/DefaultTagRepository.java
  src/main/java/com/adoonge/seedzip/tag/repository/TagRepository.java
  src/main/java/com/adoonge/seedzip/tag/repository/UsedDefaultTagRepository.java
  src/main/java/com/adoonge/seedzip/tag/repository/UsedTagRepository.java
  src/main/java/com/adoonge/seedzip/tag/service/TagService.java
Labels: Bug 🐞, Feature ✨, Refactor ♻️

#72 Feat: 콘텐츠 필터링 및 검색 기능 구현 (#71)
  build.gradle
  src/main/java/com/adoonge/seedzip/content/controller/ContentsController.java
  src/main/java/com/adoonge/seedzip/content/dto/request/ContentsFilterRequest.java
  src/main/java/com/adoonge/seedzip/content/repository/ContentsRepositoryCustom.java
  src/main/java/com/adoonge/seedzip/content/repository/ContentsRepositoryImpl.java
  src/main/java/com/adoonge/seedzip/content/service/ContentsService.java
  src/main/java/com/adoonge/seedzip/global/config/QueryDslConfig.java
Labels: Feature ✨

#73 Feat : 커스텀 필터 기능 구현 (#70)
  build.gradle
  src/main/java/com/adoonge/seedzip/content/repository/ContentsRepositoryCustom.java
  src/main/java/com/adoonge/seedzip/content/repository/ContentsRepositoryImpl.java
  src/main/java/com/adoonge/seedzip/content/service/ContentsService.java
  src/main/java/com/adoonge/seedzip/filter/controller/FilterController.java
  src/main/java/com/adoonge/seedzip/filter/domain/Filter.java
  src/main/java/com/adoonge/seedzip/filter/domain/FilterTag.java
  src/main/java/com/adoonge/seedzip/filter/dto/AddFilterRequest.java
  src/main/java/com/adoonge/seedzip/filter/repository/FilterRepository.java
  src/main/java/com/adoonge/seedzip/filter/repository/FilterRepositoryCustom.java
  src/main/java/com/adoonge/seedzip/filter/repository/FilterTagRepository.java
  src/main/java/com/adoonge/seedzip/filter/service/FilterService.java
  src/main/java/com/adoonge/seedzip/global/config/QueryDslConfig.java
  src/main/java/com/adoonge/seedzip/global/exception/ErrorCode.java
Labels: Bug 🐞, Feature ✨

#75 Feat: 콘텐츠 생성 API 수정 (#8)
  src/main/java/com/adoonge/seedzip/content/controller/ContentsController.java
  src/main/java/com/adoonge/seedzip/content/domain/Contents.java
  src/main/java/com/adoonge/seedzip/content/dto/request/ContentsRequest.java
  src/main/java/com/adoonge/seedzip/content/service/ContentsService.java
Labels: Feature ✨

#77 Feat: 마이페이지 기능 구현 (#76)
  src/main/java/com/adoonge/seedzip/bookmark/domain/Bookmark.java
  src/main/java/com/adoonge/seedzip/category/domain/Category.java
  src/main/java/com/adoonge/seedzip/content/domain/Contents.java
  src/main/java/com/adoonge/seedzip/filter/domain/Filter.java
  src/main/java/com/adoonge/seedzip/filter/domain/FilterTag.java
  src/main/java/com/adoonge/seedzip/member/controller/MemberController.java
  src/main/java/com/adoonge/seedzip/member/domain/Member.java
  src/main/java/com/adoonge/seedzip/member/dto/request/UpdateMemberRequest.java
  src/main/java/com/adoonge/seedzip/member/dto/response/MemberInformationResponse.java
  src/main/java/com/adoonge/seedzip/member/repository/MemberRepository.java
  src/main/java/com/adoonge/seedzip/member/service/MemberService.java
  src/main/java/com/adoonge/seedzip/tag/domain/UsedDefaultTag.java
Labels: Feature ✨

#78 Feat : 커스텀 필터 조회 구현 및 수정 (#70)
  src/main/java/com/adoonge/seedzip/content/repository/ContentsRepositoryImpl.java
  src/main/java/com/adoonge/seedzip/filter/controller/FilterController.java
  src/main/java/com/adoonge/seedzip/filter/dto/AddFilterRequest.java
  src/main/java/com/adoonge/seedzip/filter/dto/FilterResponse.java
  src/main/java/com/adoonge/seedzip/filter/repository/FilterRepository.java
  src/main/java/com/adoonge/seedzip/filter/repository/FilterRepositoryCustom.java
  src/main/java/com/adoonge/seedzip/filter/service/FilterService.java
Labels: Chore ⚙️, Feature ✨

#79 Feat : 커스텀 필터 삭제 및 수정 로직 구현 (#70)
  src/main/java/com/adoonge/seedzip/content/repository/ContentsRepositoryImpl.java
  src/main/java/com/adoonge/seedzip/filter/controller/FilterController.java
  src/main/java/com/adoonge/seedzip/filter/domain/Filter.java
  src/main/java/com/adoonge/seedzip/filter/dto/request/AddFilterRequest.java
  src/main/java/com/adoonge/seedzip/filter/dto/request/UpdateFilterNameRequest.java
  src/main/java/com/adoonge/seedzip/filter/dto/request/UpdateFilterRequest.java
  src/main/java/com/adoonge/seedzip/filter/dto/response/FilterInfoResponse.java
  src/main/java/com/adoonge/seedzip/filter/dto/response/FilterResponse.java
  src/main/java/com/adoonge/seedzip/filter/repository/FilterRepository.java
  src/main/java/com/adoonge/seedzip/filter/repository/FilterTagRepository.java
  src/main/java/com/adoonge/seedzip/filter/service/FilterService.java
Labels: Feature ✨

#80 Refactor: 이미지 관련 추천시 아닌 이미지 링크가 아닌, 이미지 자체를 받도록 리팩토링 (#56)
  src/main/java/com/adoonge/seedzip/recommendation/controller/RecommendationController.java
  src/main/java/com/adoonge/seedzip/recommendation/service/RecommendationService.java
Labels: Refactor ♻️

#81 Feat : 콘텐츠 내용 수정과 수정된 파일 업로드 API 분리 (#8)
  src/main/java/com/adoonge/seedzip/content/controller/ContentsController.java
  src/main/java/com/adoonge/seedzip/content/service/ContentsService.java
Labels: Feature ✨

#85 Feat : pdf 요약 구현(#56)
  build.gradle
  src/main/java/com/adoonge/seedzip/recommendation/controller/RecommendationController.java
  src/main/java/com/adoonge/seedzip/recommendation/dto/request/ChatGPTRequest.java
  src/main/java/com/adoonge/seedzip/recommendation/service/RecommendationService.java
Labels: Feature ✨

#86 Feat: 앱용 로그인 API 구현
  src/main/java/com/adoonge/seedzip/auth/controller/AuthController.java
  src/main/java/com/adoonge/seedzip/auth/service/AuthService.java
Labels: Feature ✨, Refactor ♻️

#88 Feat : 네이버 뉴스 요약 api 구현 #88
  build.gradle
  src/main/java/com/adoonge/seedzip/global/exception/ErrorCode.java
  src/main/java/com/adoonge/seedzip/recommendation/controller/RecommendationController.java
  src/main/java/com/adoonge/seedzip/recommendation/dto/request/ChatGPTRequest.java
  src/main/java/com/adoonge/seedzip/recommendation/service/NaverNewsService.java
  src/main/java/com/adoonge/seedzip/recommendation/service/RecommendationService.java
  src/main/java/com/adoonge/seedzip/recommendation/service/YouTubeService.java
Labels: Feature ✨

#89 Feat: 썸네일 수정 기능 추가 (#8)
  src/main/java/com/adoonge/seedzip/content/service/ContentsService.java
Labels: Feature ✨

#91 Infra: CI/CD 파이프라인 수정
  .github/workflows/seedzip-be-cd.yml
  src/main/java/com/adoonge/seedzip/global/HealthCheck.java
Labels: Infrastructure 🌎

#92 Docs: Swagger 설정 변경 (#90)
  src/main/java/com/adoonge/seedzip/global/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: Refactor ♻️
