Repository AdoongE/BE, pull requests merged in 2024-11, with the labels that each got.

#2 Chore: 초기 세팅
  .gitignore
  build.gradle
  docker-compose.yml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/adoonge/seedzip/SeedzipApplication.java
  src/main/java/com/adoonge/seedzip/global/HealthCheck.java
  src/main/java/com/adoonge/seedzip/global/config/SwaggerConfig.java
  src/main/java/com/adoonge/seedzip/global/dto/response/ApiResponse.java
  src/main/java/com/adoonge/seedzip/global/entity/BaseEntity.java
  src/main/java/com/adoonge/seedzip/global/exception/ErrorCode.java
  src/main/java/com/adoonge/seedzip/global/exception/SeedzipException.java
  src/main/java/com/adoonge/seedzip/global/handler/GlobalExceptionHandler.java
  src/main/resources/application.yml
  src/test/java/com/adoonge/seedzip/SeedzipApplicationTests.java
Labels: Chore ⚙️, Database 🗃️

#4 Feat: 회원가입 및 로그인 기능 구현
  build.gradle
  src/main/java/com/adoonge/seedzip/SeedzipApplication.java
  src/main/java/com/adoonge/seedzip/auth/controller/AuthController.java
  src/main/java/com/adoonge/seedzip/auth/domain/SocialType.java
  src/main/java/com/adoonge/seedzip/auth/dto/request/LoginRequest.java
  src/main/java/com/adoonge/seedzip/auth/dto/request/SignUpRequest.java
  src/main/java/com/adoonge/seedzip/auth/filter/JwtAuthenticationFilter.java
  src/main/java/com/adoonge/seedzip/auth/service/AuthService.java
  src/main/java/com/adoonge/seedzip/auth/service/CustomUserDetailService.java
  src/main/java/com/adoonge/seedzip/auth/service/JwtTokenService.java
  src/main/java/com/adoonge/seedzip/auth/util/CustomUserDetails.java
  src/main/java/com/adoonge/seedzip/global/config/SecurityConfig.java
  src/main/java/com/adoonge/seedzip/global/config/SwaggerConfig.java
  src/main/java/com/adoonge/seedzip/global/exception/ErrorCode.java
  src/main/java/com/adoonge/seedzip/member/domain/Gender.java
  src/main/java/com/adoonge/seedzip/member/domain/Member.java
  src/main/java/com/adoonge/seedzip/member/domain/Role.java
  src/main/java/com/adoonge/seedzip/member/repository/MemberRepository.java
  src/main/java/com/adoonge/seedzip/oauth/service/BasicService.java
  src/main/java/com/adoonge/seedzip/oauth/service/KakaoService.java
  src/main/java/com/adoonge/seedzip/oauth/service/OAuthService.java
  src/main/java/com/adoonge/seedzip/oauth/service/OAuthServiceFactory.java
  src/main/resources/application.yml
Labels: Feature ✨

#7 Refactor: 카카오 로그인 리팩토링
  build.gradle
  src/main/java/com/adoonge/seedzip/auth/controller/AuthController.java
  src/main/java/com/adoonge/seedzip/auth/dto/request/LoginRequest.java
  src/main/java/com/adoonge/seedzip/auth/dto/request/SignUpRequest.java
  src/main/java/com/adoonge/seedzip/auth/dto/response/LoginResponse.java
  src/main/java/com/adoonge/seedzip/auth/service/AuthService.java
  src/main/java/com/adoonge/seedzip/auth/service/CustomUserDetailService.java
  src/main/java/com/adoonge/seedzip/global/config/SecurityConfig.java
  src/main/java/com/adoonge/seedzip/global/dto/response/ApiResponse.java
  src/main/java/com/adoonge/seedzip/oauth/service/BasicService.java
  src/main/java/com/adoonge/seedzip/oauth/service/KakaoService.java
  src/main/java/com/adoonge/seedzip/oauth/service/OAuthService.java
  src/main/resources/application.yml
Labels: Refactor ♻️

#10 Docs: CICD 파이프라인 구축을 위한 문서 작성
  .github/workflows/seedzip-be-cd.yml
  .github/workflows/seedzip-be-ci.yml
  Dockerfile
  build.gradle
Labels: Infrastructure 🌎

#11 Feat: CICD 테스트 API 생성 (#9)
  src/main/java/com/adoonge/seedzip/global/HealthCheck.java
  src/main/java/com/adoonge/seedzip/global/config/SecurityConfig.java
Labels: Infrastructure 🌎

#12 Docs: CD yml 수정 (#9)
  .github/workflows/seedzip-be-cd.yml
Labels: Infrastructure 🌎

#13 Docs: cd.yml 변경
  .github/workflows/seedzip-be-cd.yml
Labels: Infrastructure 🌎

#14 Docs: Dockerfile 수정 (#9)
  Dockerfile
Labels: Infrastructure 🌎

#15 Docs: 파일 수정 (#9)
  .github/workflows/seedzip-be-cd.yml
  Dockerfile
Labels: Infrastructure 🌎

#16 Docs: 파일 수정
  .github/workflows/seedzip-be-cd.yml
Labels: Infrastructure 🌎

#17 Docs: application.yml 설정변경
  Dockerfile
  src/main/resources/application.yml
Labels: Infrastructure 🌎

#19 Test: CI/CD 테스트 2 (#9)
  src/main/java/com/adoonge/seedzip/global/HealthCheck.java
Labels: Infrastructure 🌎, Test ✅

#20 Test: CI/CD 테스트 3 (#9)
  src/main/java/com/adoonge/seedzip/global/HealthCheck.java
Labels: Infrastructure 🌎, Test ✅

#21 Test: CI/CD 테스트 4 (#9)
  src/main/java/com/adoonge/seedzip/global/HealthCheck.java
Labels: Infrastructure 🌎, Test ✅

#22 Feat: 카테고리 기능 구현 #5
  src/main/java/com/adoonge/seedzip/category/controller/CategoryController.java
  src/main/java/com/adoonge/seedzip/category/domain/Category.java
  src/main/java/com/adoonge/seedzip/category/domain/Visibility.java
  src/main/java/com/adoonge/seedzip/category/dto/request/AddCategoryRequest.java
  src/main/java/com/adoonge/seedzip/category/dto/request/UpdateCategoryRequest.java
  src/main/java/com/adoonge/seedzip/category/dto/response/CategoryResponse.java
  src/main/java/com/adoonge/seedzip/category/repository/CategoryRepository.java
  src/main/java/com/adoonge/seedzip/category/service/CategoryService.java
  src/main/java/com/adoonge/seedzip/global/exception/ErrorCode.java
Labels: Feature ✨

#23 Feat: 콘텐츠 생성 기능 구현 #8
  build.gradle
  src/main/java/com/adoonge/seedzip/auth/service/AuthService.java
  src/main/java/com/adoonge/seedzip/category/domain/Category.java
  src/main/java/com/adoonge/seedzip/category/repository/CategoryRepository.java
  src/main/java/com/adoonge/seedzip/content/controller/ContentsController.java
  src/main/java/com/adoonge/seedzip/content/domain/Contents.java
  src/main/java/com/adoonge/seedzip/content/domain/ContentsDataType.java
  src/main/java/com/adoonge/seedzip/content/domain/Document.java
  src/main/java/com/adoonge/seedzip/content/domain/Image.java
  src/main/java/com/adoonge/seedzip/content/domain/Link.java
  src/main/java/com/adoonge/seedzip/content/domain/Tag.java
  src/main/java/com/adoonge/seedzip/content/domain/mapping/CategoryContent.java
  src/main/java/com/adoonge/seedzip/content/domain/mapping/ContentTag.java
  src/main/java/com/adoonge/seedzip/content/dto/request/ContentsRequest.java
  src/main/java/com/adoonge/seedzip/content/dto/response/ContentsDocResponse.java
  src/main/java/com/adoonge/seedzip/content/dto/response/ContentsImageResponse.java
  src/main/java/com/adoonge/seedzip/content/dto/response/ContentsLinkResponse.java
  src/main/java/com/adoonge/seedzip/content/repository/CategoryContentRepository.java
  src/main/java/com/adoonge/seedzip/content/repository/ContentTagRepository.java
  src/main/java/com/adoonge/seedzip/content/repository/ContentsRepository.java
  src/main/java/com/adoonge/seedzip/content/repository/DocumentRepository.java
  src/main/java/com/adoonge/seedzip/content/repository/ImageRepository.java
  src/main/java/com/adoonge/seedzip/content/repository/LinkRepository.java
  src/main/java/com/adoonge/seedzip/content/repository/TagRepository.java
  src/main/java/com/adoonge/seedzip/content/service/ContentsService.java
  src/main/java/com/adoonge/seedzip/content/service/S3Service.java
  src/main/java/com/adoonge/seedzip/global/config/MultipartJackson2HttpMessageConverter.java
  src/main/resources/application.yml
Labels: Docs 📝, Feature ✨, Refactor ♻️

#25 Feat: 콘텐츠 조회 (전체, 카테고리 내)
  src/main/java/com/adoonge/seedzip/content/controller/ContentsController.java
  src/main/java/com/adoonge/seedzip/content/domain/Tag.java
  src/main/java/com/adoonge/seedzip/content/domain/mapping/CategoryContent.java
  src/main/java/com/adoonge/seedzip/content/dto/response/ContentsAllResponse.java
  src/main/java/com/adoonge/seedzip/content/repository/CategoryContentRepository.java
  src/main/java/com/adoonge/seedzip/content/repository/ContentTagRepository.java
  src/main/java/com/adoonge/seedzip/content/repository/ContentsRepository.java
  src/main/java/com/adoonge/seedzip/content/repository/ImageRepository.java
  src/main/java/com/adoonge/seedzip/content/service/ContentsService.java
Labels: Bug 🐞, Feature ✨

#26 Feat: 콘텐츠 상세 조회
  src/main/java/com/adoonge/seedzip/content/controller/ContentsController.java
  src/main/java/com/adoonge/seedzip/content/dto/request/ContentsRequest.java
  src/main/java/com/adoonge/seedzip/content/dto/response/ContentsAllResponse.java
  src/main/java/com/adoonge/seedzip/content/repository/ContentsRepository.java
  src/main/java/com/adoonge/seedzip/content/repository/LinkRepository.java
  src/main/java/com/adoonge/seedzip/content/service/ContentsService.java
Labels: Feature ✨

#27 Feat: 콘텐츠 생성 API 통합 (#8)
  src/main/java/com/adoonge/seedzip/content/controller/ContentsController.java
  src/main/java/com/adoonge/seedzip/content/domain/Image.java
  src/main/java/com/adoonge/seedzip/content/domain/Link.java
  src/main/java/com/adoonge/seedzip/content/dto/request/ContentsRequest.java
  src/main/java/com/adoonge/seedzip/content/dto/response/ContentsAllResponse.java
  src/main/java/com/adoonge/seedzip/content/service/ContentsService.java
Labels: Feature ✨, Refactor ♻️

#29 Feat: CORS 설정 추가 (#28)
  src/main/java/com/adoonge/seedzip/global/config/WebConfig.java
Labels: Feature ✨

#30 Feat: CORS 설정 추가 (#28)
  src/main/java/com/adoonge/seedzip/global/config/SecurityConfig.java
  src/main/java/com/adoonge/seedzip/global/config/WebConfig.java
Labels: Feature ✨

#31 Feat: CORS 설정 추가 (#28)
  src/main/java/com/adoonge/seedzip/global/config/SecurityConfig.java
Labels: Feature ✨

#33 Feat: allowCredentials 제거 (#28)
  src/main/java/com/adoonge/seedzip/global/config/CorsMvcConfig.java
Labels: Feature ✨

#36 Refact : CategoryResponse 응답 변경 (#5)
  src/main/java/com/adoonge/seedzip/category/dto/response/CategoryResponse.java
Labels: Refactor ♻️

#39 Feat : 콘텐츠 상세 조회 이미지, 문서 추가 (#8)
  src/main/java/com/adoonge/seedzip/content/dto/response/ContentsAllResponse.java
  src/main/java/com/adoonge/seedzip/content/repository/DocumentRepository.java
  src/main/java/com/adoonge/seedzip/content/repository/ImageRepository.java
  src/main/java/com/adoonge/seedzip/content/service/ContentsService.java
Labels: Feature ✨

#37 Feat : 카테고리 북마크 관련 수정 #5
  src/main/java/com/adoonge/seedzip/bookmark/domain/Bookmark.java
  src/main/java/com/adoonge/seedzip/bookmark/dto/response/BookmarkResponse.java
  src/main/java/com/adoonge/seedzip/category/domain/Category.java
Labels: Feature ✨, Refactor ♻️

#38 Feat: 회원가입 데이터 검증 기능 구현 #3
  build.gradle
  src/main/java/com/adoonge/seedzip/auth/controller/AuthController.java
  src/main/java/com/adoonge/seedzip/auth/dto/request/SignUpRequest.java
  src/main/java/com/adoonge/seedzip/global/config/SecurityConfig.java
  src/main/java/com/adoonge/seedzip/global/exception/ErrorCode.java
  src/main/java/com/adoonge/seedzip/global/filter/FilterExceptionHandler.java
  src/main/java/com/adoonge/seedzip/global/handler/GlobalExceptionHandler.java
Labels: Bug 🐞, Feature ✨, Refactor ♻️

#40 Feat: CORS 설정에 PATCH 추가
  src/main/java/com/adoonge/seedzip/global/config/CorsMvcConfig.java
  src/main/java/com/adoonge/seedzip/global/config/SecurityConfig.java
Labels: Bug 🐞

#41 Feat: withCredentials 헤더 추가 (#28)
  src/main/java/com/adoonge/seedzip/global/config/CorsMvcConfig.java
  src/main/java/com/adoonge/seedzip/global/config/SecurityConfig.java
Labels: Bug 🐞

#42 Debug : @PathVariable 수정 (#8)
  src/main/java/com/adoonge/seedzip/content/controller/ContentsController.java
Labels: Bug 🐞

#45 Fix : category가 null이면 default category 찾아서 저장하는 로직 추가 (#8)
  src/main/java/com/adoonge/seedzip/category/repository/CategoryRepository.java
  src/main/java/com/adoonge/seedzip/content/service/ContentsService.java
Labels: Bug 🐞

#46 Feat : contents 상세 조회 시, thumbnailImage에 인덱스 전달 (#8)
  src/main/java/com/adoonge/seedzip/content/service/ContentsService.java
Labels: Feature ✨

#47 Feat : 문서 콘텐츠 저장 시, 썸네일 추가 (#8)
  src/main/java/com/adoonge/seedzip/content/domain/Document.java
  src/main/java/com/adoonge/seedzip/content/repository/DocumentRepository.java
  src/main/java/com/adoonge/seedzip/content/service/ContentsService.java
Labels: Feature ✨

#48 Feat : 카테고리 관련 수정 (#5)
  src/main/java/com/adoonge/seedzip/category/domain/Category.java
  src/main/java/com/adoonge/seedzip/category/service/CategoryService.java
  src/main/java/com/adoonge/seedzip/content/repository/ContentsRepository.java
  src/main/java/com/adoonge/seedzip/global/exception/ErrorCode.java
Labels: Feature ✨

#52 Feat : 콘텐츠 수정 API (링크) 추가 (#8)
  src/main/java/com/adoonge/seedzip/content/controller/ContentsController.java
  src/main/java/com/adoonge/seedzip/content/domain/Document.java
  src/main/java/com/adoonge/seedzip/content/domain/Image.java
  src/main/java/com/adoonge/seedzip/content/domain/mapping/CategoryContent.java
  src/main/java/com/adoonge/seedzip/content/domain/mapping/ContentTag.java
  src/main/java/com/adoonge/seedzip/content/dto/request/ContentsRequest.java
  src/main/java/com/adoonge/seedzip/content/repository/CategoryContentRepository.java
  src/main/java/com/adoonge/seedzip/content/repository/ContentTagRepository.java
  src/main/java/com/adoonge/seedzip/content/repository/DocumentRepository.java
  src/main/java/com/adoonge/seedzip/content/repository/ImageRepository.java
  src/main/java/com/adoonge/seedzip/content/repository/LinkRepository.java
  src/main/java/com/adoonge/seedzip/content/service/ContentsService.java
  src/main/java/com/adoonge/seedzip/content/service/S3Service.java
Labels: Feature ✨

#54 Feat : 콘텐츠 수정 API 수정 - S3에서 기존 객체 삭제 안되는 부분 수정 필요 (#8)
  src/main/java/com/adoonge/seedzip/content/service/ContentsService.java
  src/main/java/com/adoonge/seedzip/content/service/S3Service.java
Labels: Feature ✨

#55 Feat : 태그 기능 세분화 #50
  src/main/java/com/adoonge/seedzip/content/domain/Tag.java
  src/main/java/com/adoonge/seedzip/content/domain/mapping/ContentTag.java
  src/main/java/com/adoonge/seedzip/content/repository/ContentTagRepository.java
  src/main/java/com/adoonge/seedzip/content/service/ContentsService.java
  src/main/java/com/adoonge/seedzip/global/exception/ErrorCode.java
  src/main/java/com/adoonge/seedzip/tag/controller/TagController.java
  src/main/java/com/adoonge/seedzip/tag/domain/CustomTag.java
  src/main/java/com/adoonge/seedzip/tag/domain/DefaultTag.java
  src/main/java/com/adoonge/seedzip/tag/domain/Tag.java
  src/main/java/com/adoonge/seedzip/tag/domain/UsedDefaultTag.java
  src/main/java/com/adoonge/seedzip/tag/domain/type/DefaultTagType.java
  src/main/java/com/adoonge/seedzip/tag/dto/TagResponse.java
  src/main/java/com/adoonge/seedzip/tag/repository/CustomTagRepository.java
  src/main/java/com/adoonge/seedzip/tag/repository/DefaultTagRepository.java
  src/main/java/com/adoonge/seedzip/tag/repository/TagRepository.java
  src/main/java/com/adoonge/seedzip/tag/repository/UsedDefaultTagRepository.java
  src/main/java/com/adoonge/seedzip/tag/repository/UsedTagRepository.java
  src/main/java/com/adoonge/seedzip/tag/service/TagService.java
Labels: Database 🗃️, Feature ✨

#58 Feat: 콘텐츠 수정 API - 태그 수정에 따른 코드 수정
  src/main/java/com/adoonge/seedzip/content/service/ContentsService.java
Labels: Feature ✨

#59 Feat : 콘텐츠 상세 조회 - 파일 제목 추가 (#8)
  src/main/java/com/adoonge/seedzip/content/dto/response/ContentsAllResponse.java
  src/main/java/com/adoonge/seedzip/content/service/ContentsService.java
Labels: Feature ✨

#61 Feat: ChatGPT 관련 설정을 진행한다.
  src/main/java/com/adoonge/seedzip/global/config/SecurityConfig.java
  src/main/java/com/adoonge/seedzip/summary/config/OpenAiConfig.java
  src/main/java/com/adoonge/seedzip/summary/controller/SummaryController.java
  src/main/java/com/adoonge/seedzip/summary/dto/Message.java
  src/main/java/com/adoonge/seedzip/summary/dto/TextMessage.java
  src/main/java/com/adoonge/seedzip/summary/dto/request/ChatGPTRequest.java
  src/main/java/com/adoonge/seedzip/summary/dto/request/Content.java
  src/main/java/com/adoonge/seedzip/summary/dto/request/ImageContent.java
  src/main/java/com/adoonge/seedzip/summary/dto/request/ImageMessage.java
  src/main/java/com/adoonge/seedzip/summary/dto/request/ImageUrl.java
  src/main/java/com/adoonge/seedzip/summary/dto/request/TextContent.java
  src/main/java/com/adoonge/seedzip/summary/dto/response/ChatGPTResponse.java
  src/main/java/com/adoonge/seedzip/summary/dto/response/Choice.java
  src/main/java/com/adoonge/seedzip/summary/service/SummaryService.java
  src/main/resources/application.yml
Labels: Feature ✨

#62 Feat : 콘텐츠 삭제 수정 완료 - S3에서 삭제 (#8)
  src/main/java/com/adoonge/seedzip/content/repository/CategoryContentRepository.java
  src/main/java/com/adoonge/seedzip/content/service/ContentsService.java
  src/main/java/com/adoonge/seedzip/content/service/S3Service.java
Labels: Feature ✨

#64 Feat: GPT에서 받아온 이미지 요약 결과 파싱하는 로직 추가 (#56)
  src/main/java/com/adoonge/seedzip/summary/controller/SummaryController.java
  src/main/java/com/adoonge/seedzip/summary/dto/request/ChatGPTRequest.java
  src/main/java/com/adoonge/seedzip/summary/dto/response/ImageSummaryResponse.java
  src/main/java/com/adoonge/seedzip/summary/service/SummaryService.java
Labels: Feature ✨, Refactor ♻️
