Repository AdoongE/BE, pull requests merged in 2025-05, with the labels that each got.

#129 Refactor/custom filter 관련 리팩토링 #121
  src/main/java/com/adoonge/seedzip/filter/controller/FilterController.java
  src/main/java/com/adoonge/seedzip/filter/repository/FilterRepositoryCustom.java
  src/main/java/com/adoonge/seedzip/filter/repository/FilterRepositoryImpl.java
  src/main/java/com/adoonge/seedzip/global/exception/ErrorCode.java
  src/main/java/com/adoonge/seedzip/seed/domain/Seed.java
  src/main/java/com/adoonge/seedzip/seed/dto/projection/CategorySeedProjection.java
  src/main/java/com/adoonge/seedzip/seed/dto/projection/FileSeedProjection.java
  src/main/java/com/adoonge/seedzip/seed/dto/projection/SeedTagProjection.java
  src/main/java/com/adoonge/seedzip/seed/repository/CategorySeedRepository.java
  src/main/java/com/adoonge/seedzip/seed/repository/FileRepository.java
  src/main/java/com/adoonge/seedzip/seed/repository/SeedRepositoryCustom.java
  src/main/java/com/adoonge/seedzip/seed/repository/SeedRepositoryImpl.java
  src/main/java/com/adoonge/seedzip/seed/repository/SeedTagRepository.java
  src/main/java/com/adoonge/seedzip/seed/service/SeedService.java
  src/main/resources/application.yml
Labels: Refactor ♻️

#130 Refactor: 기존 조회 코드 DTO Projection 방식으로 리팩토링 완료 #121
  src/main/java/com/adoonge/seedzip/seed/service/SeedService.java
  src/main/resources/application.yml
Labels: Database 🗃️, Refactor ♻️

#132 Refactor: 소셜 로그인 리팩토링 (#118)
  build.gradle
  src/main/java/com/adoonge/seedzip/auth/controller/AuthController.java
  src/main/java/com/adoonge/seedzip/auth/dto/request/SignUpRequest.java
  src/main/java/com/adoonge/seedzip/auth/dto/response/oauth/google/GoogleTokenResponse.java
  src/main/java/com/adoonge/seedzip/auth/dto/response/oauth/google/GoogleUserInfoResponse.java
  src/main/java/com/adoonge/seedzip/auth/dto/response/oauth/kakao/KakaoTokenResponse.java
  src/main/java/com/adoonge/seedzip/auth/dto/response/oauth/kakao/KakaoUserInfoResponse.java
  src/main/java/com/adoonge/seedzip/auth/dto/response/oauth/naver/NaverTokenResponse.java
  src/main/java/com/adoonge/seedzip/auth/dto/response/oauth/naver/NaverUserInfoResponse.java
  src/main/java/com/adoonge/seedzip/auth/service/AuthService.java
  src/main/java/com/adoonge/seedzip/auth/service/oauth/BasicService.java
  src/main/java/com/adoonge/seedzip/auth/service/oauth/GoogleService.java
  src/main/java/com/adoonge/seedzip/auth/service/oauth/KakaoService.java
  src/main/java/com/adoonge/seedzip/auth/service/oauth/NaverService.java
  src/main/java/com/adoonge/seedzip/auth/service/oauth/OAuthService.java
  src/main/java/com/adoonge/seedzip/auth/service/oauth/OAuthServiceFactory.java
  src/main/java/com/adoonge/seedzip/global/config/WebClientConfig.java
  src/main/java/com/adoonge/seedzip/global/exception/ErrorCode.java
  src/main/java/com/adoonge/seedzip/oauth/service/BasicService.java
  src/main/java/com/adoonge/seedzip/oauth/service/GoogleService.java
  src/main/java/com/adoonge/seedzip/oauth/service/KakaoService.java
  src/main/java/com/adoonge/seedzip/oauth/service/NaverService.java
  src/main/java/com/adoonge/seedzip/oauth/service/OAuthService.java
Labels: Refactor ♻️

#136 Feat: 공지사항/이용약관/FAQ CRUD API 구현 (#134)
  src/main/java/com/adoonge/seedzip/auth/dto/request/SignUpRequest.java
  src/main/java/com/adoonge/seedzip/auth/util/CustomUserDetails.java
  src/main/java/com/adoonge/seedzip/faq/controller/FaqController.java
  src/main/java/com/adoonge/seedzip/faq/domain/Faq.java
  src/main/java/com/adoonge/seedzip/faq/domain/FaqType.java
  src/main/java/com/adoonge/seedzip/faq/dto/request/FaqCreateRequest.java
  src/main/java/com/adoonge/seedzip/faq/dto/request/FaqUpdateRequest.java
  src/main/java/com/adoonge/seedzip/faq/dto/response/FaqResponse.java
  src/main/java/com/adoonge/seedzip/faq/repository/FaqRepository.java
  src/main/java/com/adoonge/seedzip/faq/service/FaqService.java
  src/main/java/com/adoonge/seedzip/global/exception/ErrorCode.java
  src/main/java/com/adoonge/seedzip/member/domain/Member.java
  src/main/java/com/adoonge/seedzip/notice/controller/NoticeController.java
  src/main/java/com/adoonge/seedzip/notice/domain/Notice.java
  src/main/java/com/adoonge/seedzip/notice/dto/request/NoticeCreateRequest.java
  src/main/java/com/adoonge/seedzip/notice/dto/request/NoticeUpdateRequest.java
  src/main/java/com/adoonge/seedzip/notice/dto/response/NoticeDetailResponse.java
  src/main/java/com/adoonge/seedzip/notice/dto/response/NoticeResponse.java
  src/main/java/com/adoonge/seedzip/notice/repository/NoticeRepository.java
  src/main/java/com/adoonge/seedzip/notice/service/NoticeService.java
  src/main/java/com/adoonge/seedzip/term/controller/TermController.java
  src/main/java/com/adoonge/seedzip/term/dto/request/TermUpdateRequest.java
  src/main/java/com/adoonge/seedzip/term/dto/response/TermResponse.java
  src/main/java/com/adoonge/seedzip/term/entity/Term.java
  src/main/java/com/adoonge/seedzip/term/entity/TermType.java
  src/main/java/com/adoonge/seedzip/term/repository/TermRepository.java
  src/main/java/com/adoonge/seedzip/term/service/TermService.java
Labels: Admin 💻, Feature ✨

#138 Refactor/remove annotation #137
  src/main/java/com/adoonge/seedzip/category/service/CategoryService.java
  src/main/java/com/adoonge/seedzip/content/controller/ContentsController.java
  src/main/java/com/adoonge/seedzip/content/domain/Contents.java
  src/main/java/com/adoonge/seedzip/content/domain/Document.java
  src/main/java/com/adoonge/seedzip/content/domain/Image.java
  src/main/java/com/adoonge/seedzip/content/domain/Link.java
  src/main/java/com/adoonge/seedzip/content/domain/mapping/CategoryContent.java
  src/main/java/com/adoonge/seedzip/content/domain/mapping/ContentTag.java
  src/main/java/com/adoonge/seedzip/content/repository/CategoryContentRepository.java
  src/main/java/com/adoonge/seedzip/content/repository/ContentTagRepository.java
  src/main/java/com/adoonge/seedzip/content/repository/ContentsRepository.java
  src/main/java/com/adoonge/seedzip/content/repository/ContentsRepositoryCustom.java
  src/main/java/com/adoonge/seedzip/content/repository/ContentsRepositoryImpl.java
  src/main/java/com/adoonge/seedzip/content/repository/DocumentRepository.java
  src/main/java/com/adoonge/seedzip/content/repository/ImageRepository.java
  src/main/java/com/adoonge/seedzip/content/repository/LinkRepository.java
  src/main/java/com/adoonge/seedzip/content/service/ContentsService.java
  src/main/java/com/adoonge/seedzip/filter/controller/FilterController.java
  src/main/java/com/adoonge/seedzip/seed/repository/SeedRepository.java
  src/main/java/com/adoonge/seedzip/seed/repository/SeedRepositoryImpl.java
Labels: Refactor ♻️

#140 Refactor: 회원가입시 성별 선택으로 변경 (#139)
  src/main/java/com/adoonge/seedzip/auth/dto/request/SignUpRequest.java
Labels: Refactor ♻️

#143 Refactor: 미분류 카테고리 추가 완료 (#142)
  src/main/java/com/adoonge/seedzip/auth/service/AuthService.java
  src/main/java/com/adoonge/seedzip/category/domain/Category.java
  src/main/java/com/adoonge/seedzip/category/dto/request/AddCategoryRequest.java
  src/main/java/com/adoonge/seedzip/category/service/CategoryService.java
  src/main/java/com/adoonge/seedzip/global/exception/ErrorCode.java
  src/main/java/com/adoonge/seedzip/seed/controller/SeedController.java
  src/main/java/com/adoonge/seedzip/seed/dto/request/SeedRequest.java
  src/main/java/com/adoonge/seedzip/seed/service/SeedService.java
Labels: Refactor ♻️

#145 Feat : 앱 메인페이지 구현 및 조회수 로직 추가 (#141)
  build.gradle
  src/main/java/com/adoonge/seedzip/SeedzipApplication.java
  src/main/java/com/adoonge/seedzip/app/controller/AppController.java
  src/main/java/com/adoonge/seedzip/app/dto/response/AppMainResponse.java
  src/main/java/com/adoonge/seedzip/app/service/AppService.java
  src/main/java/com/adoonge/seedzip/global/config/RedisCacheConfig.java
  src/main/java/com/adoonge/seedzip/global/config/RedisConfig.java
  src/main/java/com/adoonge/seedzip/seed/controller/SeedController.java
  src/main/java/com/adoonge/seedzip/seed/domain/Seed.java
  src/main/java/com/adoonge/seedzip/seed/dto/SeedStatisticsDTO.java
  src/main/java/com/adoonge/seedzip/seed/repository/SeedRepository.java
  src/main/java/com/adoonge/seedzip/seed/repository/SeedRepositoryCustom.java
  src/main/java/com/adoonge/seedzip/seed/repository/SeedRepositoryImpl.java
  src/main/java/com/adoonge/seedzip/seed/service/SeedCacheService.java
  src/main/java/com/adoonge/seedzip/seed/service/SeedScheduledService.java
  src/main/java/com/adoonge/seedzip/seed/service/SeedService.java
  src/main/resources/application.yml
Labels: Feature ✨

#146 Debug : 배치주기 변경 및 네이밍 변경 (#141)
  src/main/java/com/adoonge/seedzip/app/controller/AppController.java
  src/main/java/com/adoonge/seedzip/app/dto/response/AppUserStatisticsResponse.java
  src/main/java/com/adoonge/seedzip/app/service/AppService.java
  src/main/java/com/adoonge/seedzip/seed/service/SeedScheduledService.java
Labels: Bug 🐞, Refactor ♻️
