Repository AdoongE/BE, pull requests merged in 2025-04, with the labels that each got.

#124 Feat : 전체 씨드 모아보기, 카테고리 내 씨드 모아보기 기능 구현 (#121)
  src/main/java/com/adoonge/seedzip/seed/controller/SeedController.java
  src/main/java/com/adoonge/seedzip/seed/dto/response/SeedResponse.java
  src/main/java/com/adoonge/seedzip/seed/repository/CategorySeedRepository.java
  src/main/java/com/adoonge/seedzip/seed/repository/FileRepository.java
  src/main/java/com/adoonge/seedzip/seed/repository/SeedRepository.java
  src/main/java/com/adoonge/seedzip/seed/repository/SeedTagRepository.java
  src/main/java/com/adoonge/seedzip/seed/service/SeedService.java
Labels: Feature ✨, Refactor ♻️

#125 [Refactor] Seed의 POST 관련 메서드 리팩토링 #121
  src/main/java/com/adoonge/seedzip/category/repository/CategoryRepository.java
  src/main/java/com/adoonge/seedzip/category/service/CategoryService.java
  src/main/java/com/adoonge/seedzip/content/service/ContentsService.java
  src/main/java/com/adoonge/seedzip/global/exception/ErrorCode.java
  src/main/java/com/adoonge/seedzip/seed/controller/SeedController.java
  src/main/java/com/adoonge/seedzip/seed/domain/File.java
  src/main/java/com/adoonge/seedzip/seed/dto/SeedDTO.java
  src/main/java/com/adoonge/seedzip/seed/dto/reqeust/SeedRequest.java
  src/main/java/com/adoonge/seedzip/seed/dto/response/SeedResponse.java
  src/main/java/com/adoonge/seedzip/seed/service/FileService.java
  src/main/java/com/adoonge/seedzip/seed/service/SeedService.java
Labels: Refactor ♻️

#126 Refactor: 씨드 상세보기 기능 리팩토링 및 구현
  src/main/java/com/adoonge/seedzip/global/exception/ErrorCode.java
  src/main/java/com/adoonge/seedzip/seed/controller/SeedController.java
  src/main/java/com/adoonge/seedzip/seed/dto/response/SeedResponse.java
  src/main/java/com/adoonge/seedzip/seed/repository/FileRepository.java
  src/main/java/com/adoonge/seedzip/seed/service/SeedService.java
Labels: Refactor ♻️

#127 Debug : 파일 일부 필드 null로 들어가는 문제 (#121)
  src/main/java/com/adoonge/seedzip/seed/controller/SeedController.java
  src/main/java/com/adoonge/seedzip/seed/domain/File.java
  src/main/java/com/adoonge/seedzip/seed/service/FileService.java
Labels: Bug 🐞

#128 Feat: 전체 씨드, 카테고리 내 씨드 필터링 및 검색 기능 구현 (#121)
  src/main/java/com/adoonge/seedzip/seed/controller/SeedController.java
  src/main/java/com/adoonge/seedzip/seed/dto/request/SeedFilteringRequest.java
  src/main/java/com/adoonge/seedzip/seed/dto/request/SeedRequest.java
  src/main/java/com/adoonge/seedzip/seed/dto/response/SeedResponse.java
  src/main/java/com/adoonge/seedzip/seed/repository/SeedRepositoryCustom.java
  src/main/java/com/adoonge/seedzip/seed/repository/SeedRepositoryImpl.java
  src/main/java/com/adoonge/seedzip/seed/service/SeedService.java
Labels: Feature ✨, Refactor ♻️
