Repository AdoongE/BE, pull requests merged in 2025-01, with the labels that each got.

#95 Fix: s3 이미지 삭제 에러 해결 (#8)
  src/main/java/com/adoonge/seedzip/content/service/S3Service.java
Labels: Bug 🐞

#97 Refactor: 콘텐츠 간략화 및 생성 기능 리팩토링
  src/main/java/com/adoonge/seedzip/content/controller/ContentsController.java
  src/main/java/com/adoonge/seedzip/content/dto/request/ContentsUrlRequest.java
  src/main/java/com/adoonge/seedzip/content/dto/request/S3DeleteRequest.java
  src/main/java/com/adoonge/seedzip/content/service/ContentsService.java
  src/main/java/com/adoonge/seedzip/global/config/SecurityConfig.java
  src/main/java/com/adoonge/seedzip/recommendation/controller/RecommendationController.java
  src/main/java/com/adoonge/seedzip/recommendation/service/RecommendationService.java
  src/main/java/com/adoonge/seedzip/simplification/config/OpenAiConfig.java
  src/main/java/com/adoonge/seedzip/simplification/controller/SimplificationController.java
  src/main/java/com/adoonge/seedzip/simplification/dto/Message.java
  src/main/java/com/adoonge/seedzip/simplification/dto/TextMessage.java
  src/main/java/com/adoonge/seedzip/simplification/dto/request/ChatGPTRequest.java
  src/main/java/com/adoonge/seedzip/simplification/dto/request/Content.java
  src/main/java/com/adoonge/seedzip/simplification/dto/request/ImageContent.java
  src/main/java/com/adoonge/seedzip/simplification/dto/request/ImageMessage.java
  src/main/java/com/adoonge/seedzip/simplification/dto/request/ImageUrl.java
  src/main/java/com/adoonge/seedzip/simplification/dto/request/TextContent.java
  src/main/java/com/adoonge/seedzip/simplification/dto/response/ChatGPTResponse.java
  src/main/java/com/adoonge/seedzip/simplification/dto/response/Choice.java
  src/main/java/com/adoonge/seedzip/simplification/dto/response/SimplificationAllResponse.java
  src/main/java/com/adoonge/seedzip/simplification/dto/response/SimplificationInfoResponse.java
  src/main/java/com/adoonge/seedzip/simplification/service/NaverNewsService.java
  src/main/java/com/adoonge/seedzip/simplification/service/SimplificationService.java
  src/main/java/com/adoonge/seedzip/simplification/service/YouTubeService.java
Labels: Refactor ♻️

#99 Feat: 콘텐츠 이름이 없다면 createdAt 반환하도록 수정
  src/main/java/com/adoonge/seedzip/content/service/ContentsService.java
Labels: Feature ✨

#100 Feat : 콘텐츠 이름이 빈 문자열일 경우도 createdAt으로 반환 (#8)
  src/main/java/com/adoonge/seedzip/content/service/ContentsService.java
Labels: Feature ✨

#103 Refactor: 필터링 및 검색 시 최근에 추가된 콘텐츠가 먼저 나오도록 수정 (#101)
  src/main/java/com/adoonge/seedzip/content/service/ContentsService.java
Labels: Refactor ♻️

#105 Docs: README 업데이트 (#104)
  README.md
Labels: Docs 📝

#106 Refactor: 필터링 및 검색 시 콘텐츠 내용도 응답에 추가 (#101)
  src/main/java/com/adoonge/seedzip/content/controller/ContentsController.java
  src/main/java/com/adoonge/seedzip/content/dto/response/ContentsAllResponse.java
  src/main/java/com/adoonge/seedzip/content/service/ContentsService.java
Labels: Refactor ♻️

#110 Feat: 프론트엔드 앱 개발을 위한 CORS 설정 추가 (#108)
  src/main/java/com/adoonge/seedzip/global/config/CorsMvcConfig.java
  src/main/java/com/adoonge/seedzip/global/config/SecurityConfig.java
Labels: Refactor ♻️

#112 Feat : 전체 컨텐츠 목록 및 카테고리 내 컨텐츠 목록 조회 시, 링크 주소 추가 (#101)
  src/main/java/com/adoonge/seedzip/content/service/ContentsService.java
Labels: Feature ✨

#113 Feat : 필터링 컨텐츠 목록 조회 시, 링크 주소 추가 (#101)
  src/main/java/com/adoonge/seedzip/content/service/ContentsService.java
Labels: Feature ✨
