Repository AdoongE/BE, pull requests merged in 2025-03, with the labels that each got.

#115 Chore: 서버 이전으로 인한 CD 파이프라인 수정 (#114)
  .github/workflows/seedzip-be-cd.yml
Labels: Chore ⚙️

#116 Test: CI/CD 테스트 (#114)
  src/main/java/com/adoonge/seedzip/global/HealthCheck.java
Labels: Test ✅

#120 Refactor : AI 요약 기능에 횟수 제한을 추가한다
  src/main/java/com/adoonge/seedzip/global/exception/ErrorCode.java
  src/main/java/com/adoonge/seedzip/member/domain/MemberAiUsages.java
  src/main/java/com/adoonge/seedzip/member/repository/MemberAiUsageRepository.java
  src/main/java/com/adoonge/seedzip/simplification/controller/SimplificationController.java
  src/main/java/com/adoonge/seedzip/simplification/controller/SimplificationControllerV2.java
  src/main/java/com/adoonge/seedzip/simplification/service/SimplificationService.java
Labels: Bug 🐞, Feature ✨, Refactor ♻️

#122 Refactor: 리팩토링을 위한 Seed 엔티티 생성 (#121)
  src/main/java/com/adoonge/seedzip/content/service/ContentsService.java
  src/main/java/com/adoonge/seedzip/global/service/S3Service.java
  src/main/java/com/adoonge/seedzip/seed/controller/SeedController.java
  src/main/java/com/adoonge/seedzip/seed/domain/Seed.java
  src/main/java/com/adoonge/seedzip/seed/domain/SeedType.java
  src/main/java/com/adoonge/seedzip/seed/domain/mapping/CategorySeed.java
  src/main/java/com/adoonge/seedzip/seed/domain/mapping/SeedTag.java
  src/main/java/com/adoonge/seedzip/seed/repository/CategorySeedRepository.java
  src/main/java/com/adoonge/seedzip/seed/repository/SeedRepository.java
  src/main/java/com/adoonge/seedzip/seed/repository/SeedTagRepository.java
  src/main/java/com/adoonge/seedzip/seed/service/SeedService.java
  src/main/java/com/adoonge/seedzip/simplification/service/SimplificationService.java
Labels: Feature ✨, Refactor ♻️

#123 Refact : 엔티티 구조 변경 (#121)
  src/main/java/com/adoonge/seedzip/seed/domain/File.java
  src/main/java/com/adoonge/seedzip/seed/domain/Seed.java
Labels: Refactor ♻️
